apiVersion: storage.halo.run/v1alpha1
kind: PolicyTemplate
metadata:
  name: alist
spec:
  displayName: AList 存储
  settingName: alist-policy-template-setting
---
apiVersion: v1alpha1
kind: Setting
metadata:
  name: alist-policy-template-setting
spec:
  forms:
    - group: default
      formSchema:
        - $formkit: verificationForm
          action: "/apis/alist.storage.halo.run/v1alpha1/configs/-/verify"
          label: AList 存储验证
          children:
            - $formkit: text
              name: site
              label: 站点
              validation: required
              help: AList 站点地址，如 https://alist.example.com
            - $formkit: text
              name: path
              label: 挂载路径
              help: 所填用户基本路径(可在 AList 管理 -> 用户 查看)下文件夹的路径，必须以 / 开头，支持多级目录如 /picture/2024，则全路径为{基本路径}/picture/2024，上传文件时会自动创建不存在的目录，留空表示基本路径根目录 /
            - $formkit: secret
              name: secretName
              required: true
              label: secretName
              help: 需要创建一个包含 key 为 username、password 的密钥，分别填入你的 AList 站点用户名和密码
