apiVersion: storage.halo.run/v1alpha1
kind: PolicyTemplate
metadata:
  name: alist
spec:
  displayName: AList 存储
  settingName: alist-policy-template-setting
---
apiVersion: v1alpha1
kind: Setting
metadata:
  name: alist-policy-template-setting
spec:
  forms:
    - group: default
      formSchema:
        - $formkit: verificationForm
          action: "/apis/alist.halo.run/v1alpha1/policies/alist/validation"
          label: AList 存储验证
          children:
            - $formkit: text
              name: site
              label: 站点
              validation: required
              help: AList 站点地址，如 https://alist.example.com
            - $formkit: text
              name: path
              label: 挂载路径
              validation: required
              help: AList 存储中的挂载路径，必须以 / 开头，如 /aliyun
            - $formkit: secret
              name: secretName
              required: true
              label: secretName
              help: key:username,password 填入你的 AList 站点用户名和密码